- ahoy_matey.gemspec
- lib/ahoy/stores/base_store.rb
- lib/ahoy/visit_properties.rb
- test/ahoy/visit_properties_test.rb
- test/test_helper.rb
This PR addresses issue #50. 
I noticed that this gem doesn't have any tests - so following the example of your searchkick gem, I've added a test harness using Minitest, and wrote a simple test for the VisitProperties#keys method to assert that it does the right thing. I've introduced that as a separate commit in this PR, in case you want to do something else with your testing.
> Make Ahoy.geocode option work for all stores (addresses #50)

- lib/generators/ahoy/stores/templates/active_record_events_migration.rb
- lib/generators/ahoy/stores/templates/active_record_visits_migration.rb
This removes the need to have the `uuid_generate_v4()` function in Postgres databases.
Related to #59
> Default UUID migration columns to nil

- lib/ahoy/deckhands/location_deckhand.rb
- lib/ahoy/visit_properties.rb
- lib/generators/ahoy/stores/templates/active_record_visits_migration.rb
Allowing postal code to be stored alongside latitude and longitude in the visit record.  This makes it easier to do proximity searches with geocoder on the visit model.  Postal code is available in the location so it should be an option to store it if the users desire so.
> Support for postal code and lat/lng in visit record

- vendor/assets/javascripts/ahoy.js
I've recently added Ahoy to a site that also uses Turbolinks. I've hooked it in so that `ahoy.trackView()` is called when Turbolinks' `page:load` event is fired. One issue I noticed is that the 'page' property of each '$view' event is the same when called this way.
This is because the value of the `page` variable is set once when the `ahoy.js` script is evaluated, [here](https://github.com/ankane/ahoy/blob/master/vendor/assets/javascripts/ahoy.js#L23). Updating `window.ahoy.page` has no effect because the value of the closure is inaccessible.
I'm experimenting with a version of the code where `page` is a function, but I'm not sure if this is the best solution yet.
> 'page' property is not updated when used with Turbolinks

- ahoy_matey.gemspec
- lib/ahoy/deckhands/technology_deckhand.rb
- lib/ahoy/stores/base_store.rb
1)I noted gem Browser is using string as user agent variable:
```ruby
module Browser
class Base
attr_reader :ua
def initialize(ua, accept_language: nil)
@ua = ua
end
...
def bot
@bot ||= Bot.new(ua)
end
end
module Browser
class Bot
attr_reader :ua
def initialize(ua)
@ua = ua
end
...
def downcased_ua
@downcased_ua ||= ua.downcase
end
end
end
```
But ahoy creates Browser instance with hash as user agent:
`Browser.new(ua: request.user_agent)`
And we get an error in downcased_ua `NoMethodError: undefined method downcase' for Hash`
2) Inheritors of Browser::Base (sach as Browser::Chrome) have no methods `.tv?`, `.console?`, `.tablet?` and `.mobile?`. These methods is instance's methods of Browser::Device
PS: sorry for my English and sorry if I am wrong anywhere
> fix passing argument to Browser.new

- lib/ahoy.rb
- lib/ahoy/logger_silencer.rb
Copied from https://github.com/rails/activerecord-session_store/blob/master/lib/active_record/session_store/extension/logger_silencer.rb to pull in rails 5 compatibility updates
> Update logger_silencer for Rails 5 Compatibility

- README.md
- lib/ahoy.rb
- lib/ahoy/stores/base_store.rb
This adds this setting to run the geocoding process in a custom queue (instead of `ahoy`):
```ruby
Ahoy.job_queue = :low_priority
```
> Add option to change the ActiveJob queue

- ahoy_matey.gemspec
- lib/ahoy.rb
- lib/ahoy/tracker.rb
> Stop monkey patching `Object` when including `safely_block`

- lib/ahoy.rb
- lib/ahoy/controller.rb
I needed to use ahoy from an `ActionController::API` subclass (not a subclass of `ActionController::Base`) in my Rails 5 app.
> Also include Ahoy::Controller in ActionController::API subclasses

- lib/ahoy/stores/active_record_token_store.rb
In case of any unique error was raised, we will stay with `@visit` contains an instance w/o ID.
So, all `ahoy.track` calls will raise validation error (visit is missing).
> Fetch visit using ahoy.visit_token if unique violation error was raised

- lib/ahoy/properties.rb
- lib/generators/ahoy/stores/templates/active_record_events_migration.rb
- test/properties/postgresql_jsonb_test.rb
So, I've been dogged by slow event queries for months now and have been making do by needing them less and going async when possible. Such is life. But I hit on something today: using Postgres with jsonb, I put a GIN index on the properties column of ahoy_events. Then, I tried replacing `where_properties` current implementation
```sql
WHERE properties ->> 'key' = 'value'
```
with the contains operator as such:
```sql
WHERE properties @> '{"key": "value"}'
```
and saw 2x to 10x improvements in speed.
Incidentally, since `properties @> '{"key": null}'` works just fine, we don't need to handle `v.nil?` differently.
Is there any reason we wouldn't want to take advantage of this Postgres feature?
> Uses a GIN index and the @> operator with postgresql-jsonb

- lib/generators/ahoy/stores/templates/active_record_events_migration.rb
You’re right that an index almost as large as the table is unacceptable. I read a little closer in the Postgres docs and found this beauty:
> Although the jsonb_path_ops operator class supports only queries with the @> operator, it has notable performance advantages over the default operator class jsonb_ops. A jsonb_path_ops index is usually much smaller than a jsonb_ops index over the same data, and the specificity of searches is better, particularly when queries contain keys that appear frequently in the data. ([§8.14.4](https://www.postgresql.org/docs/9.6/static/datatype-json.html#JSON-INDEXING))
Rails 5 added the ability to specify operator classes in schema.rb, so I tried it. Using `jsonb_path_ops` solves the space problem handily. It honestly almost looks too good to be true, but …
> Changes GIN index to jsonb_path_ops expression index

- vendor/assets/javascripts/ahoy.js
Instead of using jQuery's `.data` function, use the `.attr` function to prevent caching issue with elements that their data-section is changed dynamically.
1. Set data-section on any DOM element to some value. 
2. Click on it once.
3. Change it's data-section value to something else. 
4. Click on it again.
5. You will see that the second data-section you are getting in the event is the **old** data-section.
I already use this and it works perfectly.
> Fix caching issues when trying to get DOM element's data-section attribute value

- README.md
`controller_path` also stores the controller's namespace, where `controller_name` wouldn't. So for example `controller_path` would return `admin/users#show` while `controller_name` would return `users#show`.
`request.path_parameters` are any params that Rails parsed in order to route the request, e.g. in the above example it'd include the user ID
> Rails tracker example: store more useful info

- CHANGELOG.md
- app/controllers/ahoy/base_controller.rb
- lib/ahoy.rb
Moves callbacks to preserve into Ahoy configuration.
Updates the Authlogic callback to its correct name `activate_authlogic` instead of `load_authlogic`.
> Adds ability to specify the correct callbacks that should be preserved

- lib/ahoy/visit_properties.rb
The referrer was sliced by 256 chars before.
> Slicing search_keyword by 255 characters

- lib/ahoy/tracker.rb
It's really difficult to debug any issues when all exceptions are silently ignored. Exceptions should crash the application in development or test.
> Exceptions should always crash in development or test

- lib/ahoy/tracker.rb
- test/tracker_test.rb
**Why**: If someone sends a request with an Ahoy Cookie or Header that
contains an invalid UTF-8 byte, the app will raise
`ArgumentError: invalid byte sequence in UTF-8`.
**How**:  Encode the token as UTF-8, and replace any invalid or
undefined bytes with an empty string.
> Ensure tokens do not contain invalid UTF-8 bytes

- lib/ahoy.rb
- lib/ahoy/tracker.rb
Hey all, first contribution to this repo so let me know if I missed anything. This is to support a new attribute of `Ahoy`: `cookie_options`. This was added to support SameSite, but it was kept open enough to allow for further extension. All of that being said I have a feeling this may be a tad too simple. If that's the case just let me know and I'll get some more work done on it.
> Adding Ahoy.cookie_options to provide support for same site

- lib/generators/ahoy/templates/active_record_migration.rb.tt
While creating an index in column we have shown an array bracket which is a bit confusing, so removed the array brackets.
> Small Cosmetic Change

- lib/ahoy/database_store.rb
We have about 5 millions visits record in our PostgreSQL 12 db.  After doing various performance analysis on pganalyze and scout I kept seeing a huge performance hit of 1+sec to retrieve visits, google pagespeed complained about my page load time, this surprised me as visit_token is indexed
Compare these two syntaxes and performance
`Visit.where(visit_token: "4208f558-2c45-4d9d-806b-b1bf14194665").first
Visit Load (1490.7ms)  SELECT  "visits".* FROM "visits" WHERE "visits"."visit_token" = $1 ORDER BY "visits"."id" ASC LIMIT $2  [["visit_token", "4208f558-2c45-4d9d-806b-b1bf14194665"], ["LIMIT", 1]]`
`Visit.find_by(visit_token: "4208f558-2c45-4d9d-806b-b1bf14194665")
Visit Load (5.2ms)  SELECT  "visits".* FROM "visits" WHERE "visits"."visit_token" = $1 LIMIT $2  [["visit_token", …
> Speed up token retrieval

- lib/ahoy/base_store.rb
- test/tracker_test.rb
Hello @ankane, thanks for the gem.
So, we can pass `:user` directly to `Ahoy::Tracker`, but, unfortunately, it not defines one in `Ahoy::Store`.  
This request fixes that.
This can be useful, for example, when we track some events asynchronously, without `:controller`, and with some additional user's parameters usage in `Ahoy::Store#track_event`.
> Allow to pass :user to Ahoy::Store through Ahoy::Tracker
